### ISSUE TITLE
Tengine/2.1.1

### ISSUE THREAD

**Issue by w00000000000000000000000** [openresty/memc-nginx-module#20]
Update: I compiled successfully module without DSO tool.
Tengine version: Tengine/2.1.1 (nginx/1.6.2)

**Comment by agentzh** [comment]
@w00000000000000000000000 Sorry, Tengine is not a supported target. Only the official nginx distribution or the OpenResty bundle are (officially) supported.

**Comment by agentzh** [comment]
@w00000000000000000000000 If you insist in using Tengine with this module, then you should really contact the Tengine maintainers instead. Again, Tengine is not supported on our side.

**Comment by w00000000000000000000000** [comment]
@agentzh I compiled successfully module without DSO tool, but get this error message "key: "/index.php" was not found by memcached" with info log.

Any ideas how to fix this?

2015/11/04 15:22:07 [info] 21505#0: *1 key: "/index.phpaction=login" was not found by memcached while reading response header from upstream, client: unix:, server: localhost, request: "GET /index.php?action=login HTTP/1.1", subrequest: "/memc", upstream: "memcached://unix:/tmp/memcached.sock:", host: "localhost", referrer: "http://localhost/index.php"
2015/11/04 15:22:10 [info] 21505#0: *4 key: "/index.php" was not found by memcached while reading response header from upstream, client: unix:, server: localhost, request: "GET /index.php HTTP/1.1", subrequest: "/memc", upstream: "memcached://unix:/tmp/memcached.sock:", host: "localhost", referrer: "http://localhost/index.php?action=login"
2015/11/04 15:22:16 [info] 21505#0: *4 key: "/index.php" was not found by memcached while reading response header from upstream, client: unix:, server: localhost, request: "GET /index.php HTTP/1.1", subrequest: "/memc", upstream: "memcached://unix:/tmp/memcached.sock:", host: "localhost", referrer: "http://localhost/index.php?action=login"
2015/11/04 15:22:19 [info] 21505#0: *12 key: "/index.phpaction=login" was not found by memcached while reading response header from upstream, client: unix:, server: localhost, request: "GET /index.php?action=login HTTP/1.1", subrequest: "/memc", upstream: "memcached://unix:/tmp/memcached.sock:", host: "localhost", referrer: "http://localhost/index.php"

STAT pid 12726
STAT uptime 30
STAT time 1446650543
STAT version 1.4.24
STAT libevent 1.4.15-stable
STAT pointer_size 64
STAT rusage_user 0.000000
STAT rusage_system 0.010000
STAT curr_connections 1
STAT total_connections 10
STAT connection_structures 2
STAT reserved_fds 20
STAT cmd_get 4
STAT cmd_set 0
STAT cmd_flush 0
STAT cmd_touch 0
STAT get_hits 0
STAT get_misses 4
STAT delete_misses 0
STAT delete_hits 0
STAT incr_misses 0
STAT incr_hits 0
STAT decr_misses 0
STAT decr_hits 0
STAT cas_misses 0
STAT cas_hits 0
STAT cas_badval 0
STAT touch_hits 0
STAT touch_misses 0
STAT auth_cmds 0
STAT auth_errors 0
STAT bytes_read 129
STAT bytes_written 4539
STAT limit_maxbytes 1073741824
STAT accepting_conns 1
STAT listen_disabled_num 0
STAT threads 4
STAT conn_yields 0
STAT hash_power_level 16
STAT hash_bytes 524288
STAT hash_is_expanding 0
STAT malloc_fails 0
STAT bytes 0
STAT curr_items 0
STAT total_items 0
STAT expired_unfetched 0
STAT evicted_unfetched 0
STAT evictions 0
STAT reclaimed 0
STAT crawler_reclaimed 0
STAT crawler_items_checked 0
STAT lrutail_reflocked 0
END

        location /memc {
            internal;

            memc_connect_timeout 100ms;
            memc_send_timeout 100ms;
            memc_read_timeout 100ms;
            memc_ignore_client_abort on;

            set $memc_key $query_string;
            set $memc_exptime 300;

            #memc_pass memcache;
	    memc_pass unix:/tmp/memcached.sock;
        }

        location / {
            root   /var/www/htdocs;
            index  index.html index.htm index.php;
        }

        location /memc-stats {
            add_header Content-Type text/plain;
            set $memc_cmd stats;
            memc_pass unix:/tmp/memcached.sock;
        }

        # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
        #
        location ~ \.php$ {
            set $key $uri$args;
            srcache_fetch GET /memc $key;
            srcache_store PUT /memc $key;
	    srcache_store_statuses 200 301 302;
            root           /var/www/htdocs;
            fastcgi_pass   unix:/var/www/run/php-fpm.sock;
            fastcgi_index  index.php;
            include        fastcgi_params;
            fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }

        # deny access to .htaccess files, if Apache's document root
        # concurs with nginx's one
        #
        #location ~ /\.ht {
        #    deny  all;
        #}
    }

}

**Comment by agentzh** [comment]
@w00000000000000000000000 They're not errors. Note the log message level is "info" there.

**Comment by w00000000000000000000000** [comment]
Login action misses all the time, don't understand why.

"key: "/index.phpaction=login" was not found by memcached"

STAT cmd_get 4
STAT get_misses 4

**Comment by agentzh** [comment]
@w00000000000000000000000 See https://github.com/openresty/srcache-nginx-module#trouble-shooting
