### ISSUE TITLE
regex for memcached version

### ISSUE THREAD

**Issue by chipitsine** [openresty/memc-nginx-module#23]
Hello,

 on Ubuntu (exactly in Travis CI),

I see the following memcached version: VERSION 1.4.14 (Ubuntu)
which does not match version regex here: https://github.com/openresty/memc-nginx-module/blob/master/t/version.t#L24

what if we change
```
"--- response_body_like: ^VERSION \d+(\.\d+)+\S*?\r\n$" with 
"--- response_body_like: ^VERSION \d+(\.\d+)+\S*?.*\r\n$" ?
```
anyway, I do not mind against any regex

currently, travis builds are failing

https://travis-ci.org/chipitsine/memc-nginx-module/jobs/132188273#L350

**Comment by chipitsine** [comment]
there're several files with that regex

```
[ilia@localhost t]$ find . -type f -exec grep VERSION {} ';' -print
--- response_body_like: ^VERSION \d+(\.\d+)+\S*?\r\n$
--- response_body_like: ^VERSION \d+(\.\d+)+\S*?\r\n$
./cmd.t
--- response_body_like: ^VERSION \d+(\.\d+)+\S*?\r\n$
./version.t
[ilia@localhost t]$ 
```

**Comment by agentzh** [comment]
I think the best regex is

```
--- response_body_like: ^VERSION \d+(\.\d+)+.*?\r\n$
```

Pull requests welcome :)
